### ISSUE TITLE
Faire du tableau de bord la page d'accueil du service

### ISSUE THREAD

**Issue by Flightan** [betagouv/holodeck-dashboard#4]
Je trouve qu'on comprend directement la proposition de valeur en arrivant sur https://dashlord.incubateur.net/#/dashboard alors qu'elle est moins claire sur https://dashlord.incubateur.net

Je proposerai d'inverser les deux et de faire de https://dashlord.incubateur.net/#/dashboard la 1ere page du service, l'utilisateur étant libre d'ensuite aller voir l'accueil qui est plutôt pour moi "En savoir plus".

**Comment by revolunet** [comment]
Je viens de faire la modif minimale, c'est mieux ? 

https://dashlord.incubateur.net

ca se passe dans ce repo : https://github.com/SocialGouv/dashlord-report-action/

**Comment by Flightan** [comment]
Très cool merci !
